export enum Command {
	Help = 'help',
	Peg = 'peg',
	Status = 'status',
	Keywords = 'keywords',
	Ping = 'ping',
	Welcome = 'welcome',
	Rotation = 'rotation',
	Winners = 'winners',
	Results = 'results',
	Reset = 'reset',
	Update = 'update',
	Finish = 'finish',
	NumberConfig = 'numberconfig',
	StringConfig = 'stringconfig',
	RoleConfig = 'roleconfig',
	Unpeg = 'unpeg',
	Location = 'location',
	UserLocation = 'userlocation',
	User = 'user'
}
